language: cpp
sudo: required
dist: trusty
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt595-trusty -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get -qq install -qq g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - g++ --version
  - sudo apt-get -qq install qt59-meta-minimal
  - source /opt/qt59/bin/qt59-env.sh
  - qmake -v

script:
    - git submodule update --init --recursive
    - /opt/qt59/bin/qmake ./tests.pro
    - make -j2
    - ./ModbusScopeTests
