language: cpp
sudo: required
dist: trusty
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt595-trusty -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get -qq install qt59-meta-minimal
  - sudo apt-get -qq install -qq g++-7
  - source /opt/qt59/bin/qt59-env.sh
  - qmake -v
  - g++ --version

script:
    - /opt/qt59/bin/qmake ./test.pro
    - make
