language: cpp
sudo: required
dist: trusty
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt595-trusty -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get -qq install qt59-meta-full
  - sudo apt-get -qq install -qq g++-7

script:
    - /opt/qt59/bin/qmake test.pro
    - make
