version: '{branch}_{build}'
image: Visual Studio 2019

platform:
  - x64

install:
  - cmd: set PATH=C:\Qt\5.12\mingw73_64\bin;%PATH%
#  - cmd: windeployqt.exe (return code isn't correct)
  
  - cmd: set PATH=C:\Qt\Tools\mingw730_64\bin;%PATH%
  - cmd: g++ -v

  - cmd: set PATH=C:\Program Files (x86)\Inno Setup 6;%PATH%
  
  # Remove git sh.exe from PATH (required for CMAKE)
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: cmake --version
  
  - cmd: echo %PATH%

  # Add OpenSSL dll's
  - cmd: dir C:\Qt\Tools\"
  - cmd: dir C:\Qt\Tools\OpenSSL\"
  - cmd: dir C:\Qt\Tools\OpenSSL\Win_x64"
  - cmd: dir C:\Qt\Tools\OpenSSL\Win_x64\bin"

