
#include "projectfilexmltestdata.h"

// clang-format off

QString ProjectFileXmlTestData::cTooLowDataLevel = QString(
    "<?xml version=\"1.0\"?>                                        \n"
    "<modbusscope datalevel=\"2\">                                  \n"
    "</modbusscope>                                                 \n"
);

QString ProjectFileXmlTestData::cTooHighDataLevel = QString(
    "<?xml version=\"1.0\"?>                                        \n"
    "<modbusscope datalevel=\"99\">                                 \n"
    "</modbusscope>                                                 \n"
);

QString ProjectFileXmlTestData::cDataLevel3Expressions = QString(
    "<?xml version=\"1.0\"?>                                                    \n"
    "<modbusscope datalevel=\"3\">                                              \n"
    "    <scope>                                                                \n"
    "        <register active=\"true\">                                         \n"
    "            <text>Data point</text>                                        \n"
    "            <expression><![CDATA[${40001}/2]]></expression>                \n"
    "            <color>#ff0000</color>                                         \n"
    "        </register>                                                        \n"
    "        <register active=\"true\">                                         \n"
    "            <text>Data point 2</text>                                      \n"
    "            <expression><![CDATA[${40002:s16b}]]></expression>             \n"
    "            <color>#0000ff</color>                                         \n"
    "        </register>                                                        \n"
    "        <register active=\"false\">                                        \n"
    "            <text>Data point 3</text>                                      \n"
    "            <expression><![CDATA[${40003@2:s16b}*10]]></expression>        \n"
    "        </register>                                                        \n"
    "    </scope>                                                               \n"
    "</modbusscope>                                                             \n"
);

QString ProjectFileXmlTestData::cDataLevel5Connection = QString(
    "<?xml version=\"1.0\"?>                                                    \n"
    "<modbusscope datalevel=\"5\">                                              \n"
    " <modbus>                                                                  \n"
    "  <connection>                                                             \n"
    "   <enabled>true</enabled>                                                 \n"
    "   <connectionid>0</connectionid>                                          \n"
    "   <type>tcp</type>                                                        \n"
    "   <ip>127.0.0.1</ip>                                                      \n"
    "   <port>502</port>                                                        \n"
    "   <portname>COM1</portname>                                               \n"
    "   <baudrate>115200</baudrate>                                             \n"
    "   <parity>0</parity>                                                      \n"
    "   <stopbits>1</stopbits>                                                  \n"
    "   <databits>8</databits>                                                  \n"
    "   <timeout>1000</timeout>                                                 \n"
    "   <persistentconnection>true</persistentconnection>                       \n"
    "  </connection>                                                            \n"
    "  <device>                                                                 \n"
    "   <deviceid>1</deviceid>                                                  \n"
    "   <name>Device 1</name>                                                   \n"
    "   <connectionid>0</connectionid>                                          \n"
    "   <slaveid>3</slaveid>                                                    \n"
    "   <consecutivemax>100</consecutivemax>                                    \n"
    "   <int32littleendian>false</int32littleendian>                            \n"
    "  </device>                                                                \n"
    "  <log>                                                                    \n"
    "   <polltime>250</polltime>                                                \n"
    "   <absolutetimes>false</absolutetimes>                                    \n"
    "   <logtofile enabled=\"true\"/>                                           \n"
    "  </log>                                                                   \n"
    " </modbus>                                                                 \n"
    "</modbusscope>                                                             \n"
);

QString ProjectFileXmlTestData::cDataLevel5MixedMulti = QString(
    "<?xml version=\"1.0\"?>                                            \n"
    "<modbusscope datalevel=\"5\">                                      \n"
    " <modbus>                                                          \n"
    "  <connection>                                                     \n"
    "   <enabled>true</enabled>                                         \n"
    "   <connectionid>0</connectionid>                                  \n"
    "   <type>serial</type>                                             \n"
    "   <ip>127.0.0.1</ip>                                              \n"
    "   <port>502</port>                                                \n"
    "   <portname>COM10</portname>                                      \n"
    "   <baudrate>38400</baudrate>                                      \n"
    "   <parity>0</parity>                                              \n"
    "   <stopbits>1</stopbits>                                          \n"
    "   <databits>8</databits>                                          \n"
    "   <timeout>500</timeout>                                          \n"
    "   <persistentconnection>true</persistentconnection>               \n"
    "  </connection>                                                    \n"
    "  <connection>                                                     \n"
    "   <enabled>true</enabled>                                         \n"
    "   <connectionid>1</connectionid>                                  \n"
    "   <type>tcp</type>                                                \n"
    "   <ip>127.0.0.1</ip>                                              \n"
    "   <port>502</port>                                                \n"
    "   <portname>COM1</portname>                                       \n"
    "   <baudrate>115200</baudrate>                                     \n"
    "   <parity>0</parity>                                              \n"
    "   <stopbits>1</stopbits>                                          \n"
    "   <databits>8</databits>                                          \n"
    "   <timeout>2000</timeout>                                         \n"
    "   <persistentconnection>true</persistentconnection>               \n"
    "  </connection>                                                    \n"
    "  <connection>                                                     \n"
    "   <enabled>false</enabled>                                        \n"
    "   <connectionid>2</connectionid>                                  \n"
    "   <type>tcp</type>                                                \n"
    "   <ip>127.0.0.1</ip>                                              \n"
    "   <port>502</port>                                                \n"
    "   <portname>COM1</portname>                                       \n"
    "   <baudrate>115200</baudrate>                                     \n"
    "   <parity>0</parity>                                              \n"
    "   <stopbits>1</stopbits>                                          \n"
    "   <databits>8</databits>                                          \n"
    "   <timeout>1000</timeout>                                         \n"
    "   <persistentconnection>true</persistentconnection>               \n"
    "  </connection>                                                    \n"
    "  <device>                                                         \n"
    "   <deviceid>1</deviceid>                                          \n"
    "   <name>Device 1 (serial 1)</name>                                \n"
    "   <connectionid>0</connectionid>                                  \n"
    "   <slaveid>1</slaveid>                                            \n"
    "   <consecutivemax>125</consecutivemax>                            \n"
    "   <int32littleendian>true</int32littleendian>                     \n"
    "  </device>                                                        \n"
    "  <device>                                                         \n"
    "   <deviceid>2</deviceid>                                          \n"
    "   <name>Device 2 (serial 2)</name>                                \n"
    "   <connectionid>0</connectionid>                                  \n"
    "   <slaveid>2</slaveid>                                            \n"
    "   <consecutivemax>125</consecutivemax>                            \n"
    "   <int32littleendian>true</int32littleendian>                     \n"
    "  </device>                                                        \n"
    "  <device>                                                         \n"
    "   <deviceid>3</deviceid>                                          \n"
    "   <name>Device 3 (TCP)</name>                                     \n"
    "   <connectionid>1</connectionid>                                  \n"
    "   <slaveid>1</slaveid>                                            \n"
    "   <consecutivemax>125</consecutivemax>                            \n"
    "   <int32littleendian>true</int32littleendian>                     \n"
    "  </device>                                                        \n"
    "  <log>                                                            \n"
    "   <polltime>250</polltime>                                        \n"
    "   <absolutetimes>false</absolutetimes>                            \n"
    "   <logtofile enabled=\"true\"/>                                   \n"
    "  </log>                                                           \n"
    " </modbus>                                                         \n"
    "</modbusscope>                                                     \n"
);

QString ProjectFileXmlTestData::cDataLevel4LegacyConnection = QString(
    "<?xml version=\"1.0\"?>                                                    \n"
    "<modbusscope datalevel=\"4\">                                              \n"
    " <modbus>                                                                  \n"
    "  <connection>                                                             \n"
    "   <enabled>true</enabled>                                                 \n"
    "   <connectionid>0</connectionid>                                          \n"
    "   <type>tcp</type>                                                        \n"
    "   <ip>127.0.0.1</ip>                                                      \n"
    "   <port>502</port>                                                        \n"
    "   <portname>COM1</portname>                                               \n"
    "   <baudrate>115200</baudrate>                                             \n"
    "   <parity>0</parity>                                                      \n"
    "   <stopbits>1</stopbits>                                                  \n"
    "   <databits>8</databits>                                                  \n"
    "   <slaveid>2</slaveid>                                                    \n"
    "   <timeout>1002</timeout>                                                 \n"
    "   <consecutivemax>122</consecutivemax>                                    \n"
    "   <int32littleendian>true</int32littleendian>                             \n"
    "   <persistentconnection>true</persistentconnection>                       \n"
    "  </connection>                                                            \n"
    "  <connection>                                                             \n"
    "   <enabled>false</enabled>                                                \n"
    "   <connectionid>1</connectionid>                                          \n"
    "   <type>tcp</type>                                                        \n"
    "   <ip>127.0.0.1</ip>                                                      \n"
    "   <port>502</port>                                                        \n"
    "   <portname>COM1</portname>                                               \n"
    "   <baudrate>115200</baudrate>                                             \n"
    "   <parity>0</parity>                                                      \n"
    "   <stopbits>1</stopbits>                                                  \n"
    "   <databits>8</databits>                                                  \n"
    "   <slaveid>3</slaveid>                                                    \n"
    "   <timeout>1000</timeout>                                                 \n"
    "   <consecutivemax>125</consecutivemax>                                    \n"
    "   <int32littleendian>true</int32littleendian>                             \n"
    "   <persistentconnection>true</persistentconnection>                       \n"
    "  </connection>                                                            \n"
    " </modbus>                                                                 \n"
    " <scope/>                                                                  \n"
    "</modbusscope>                                                             \n"
);

QString ProjectFileXmlTestData::cLogSettings = QString(
    "<?xml version=\"1.0\"?>                                    \n"
    "<modbusscope datalevel=\"5\">                              \n"
    " <modbus>                                                  \n"
    "  <log>                                                    \n"
    "   <polltime>750</polltime>                                \n"
    "   <absolutetimes>true</absolutetimes>                     \n"
    "   <logtofile enabled=\"false\"/>                          \n"
    "  </log>                                                   \n"
    " </modbus>                                                 \n"
    "</modbusscope>                                             \n"
);

QString ProjectFileXmlTestData::cScaleSliding = QString(
    "<?xml version=\"1.0\"?>                                    \n"
    "<modbusscope datalevel=\"5\">                              \n"
    "    <view>                                                 \n"
    "        <scale>                                            \n"
    "            <xaxis mode=\"sliding\">                       \n"
    "                <slidinginterval>20</slidinginterval>      \n"
    "            </xaxis>                                       \n"
    "        </scale>                                           \n"
    "    </view>                                                \n"
    "</modbusscope>                                             \n"
);

QString ProjectFileXmlTestData::cScaleMinMax = QString(
    "<?xml version=\"1.0\"?>                                    \n"
    "<modbusscope datalevel=\"5\">                              \n"
    "    <view>                                                 \n"
    "        <scale>                                            \n"
    "            <xaxis mode=\"sliding\">                       \n"
    "                <slidinginterval>20</slidinginterval>      \n"
    "            </xaxis>                                       \n"
    "            <yaxis mode=\"minmax\">                        \n"
    "                <min>0</min>                               \n"
    "                <max>25,5</max>                            \n"
    "            </yaxis>                                       \n"
    "        </scale>                                           \n"
    "    </view>                                                \n"
    "</modbusscope>                                             \n"
);

QString ProjectFileXmlTestData::cScaleWindowAuto = QString(
    "<?xml version=\"1.0\"?>                                    \n"
    "<modbusscope datalevel=\"5\">                              \n"
    "    <view>                                                 \n"
    "        <scale>                                            \n"
    "            <yaxis axis=\"0\" mode=\"windowauto\"/>        \n"
    "            <yaxis axis=\"1\" mode=\"minmax\">             \n"
    "                <min>0</min>                               \n"
    "                <max>25,5</max>                            \n"
    "            </yaxis>                                       \n"
    "        </scale>                                           \n"
    "    </view>                                                \n"
    "</modbusscope>                                             \n"
);

QString ProjectFileXmlTestData::cValueAxis = QString(
    "<?xml version=\"1.0\"?>                                                    \n"
    "<modbusscope datalevel=\"5\">                                              \n"
    "    <scope>                                                                \n"
    "        <register active=\"true\">                                         \n"
    "            <text>Data point</text>                                        \n"
    "            <expression><![CDATA[${40001}/2]]></expression>                \n"
    "            <valueaxis>0</valueaxis>                                       \n"
    "        </register>                                                        \n"
    "        <register active=\"true\">                                         \n"
    "            <text>Data point 2</text>                                      \n"
    "            <expression><![CDATA[${40002:s16b}]]></expression>             \n"
    "            <valueaxis>1</valueaxis>                                       \n"
    "        </register>                                                        \n"
    "        <register active=\"false\">                                        \n"
    "            <text>Data point 3</text>                                      \n"
    "            <expression><![CDATA[${40003@2:s16b}*10]]></expression>        \n"
    "        </register>                                                        \n"
    "    </scope>                                                               \n"
    "</modbusscope>                                                             \n"
);

QString ProjectFileXmlTestData::cValueAxisInvalid = QString(
    "<?xml version=\"1.0\"?>                                                    \n"
    "<modbusscope datalevel=\"5\">                                              \n"
    "    <scope>                                                                \n"
    "        <register active=\"true\">                                         \n"
    "            <text>Data point</text>                                        \n"
    "            <expression><![CDATA[${40001}/2]]></expression>                \n"
    "            <valueaxis>notanumber</valueaxis>                              \n"
    "        </register>                                                        \n"
    "    </scope>                                                               \n"
    "</modbusscope>                                                             \n"
);

QString ProjectFileXmlTestData::cLogFileRelativePath = QString(
    "<?xml version=\"1.0\"?>                                                    \n"
    "<modbusscope datalevel=\"5\">                                              \n"
    " <modbus>                                                                  \n"
    "  <log>                                                                    \n"
    "   <logtofile enabled=\"true\">                                            \n"
    "    <filename>subdir/output.csv</filename>                                 \n"
    "   </logtofile>                                                            \n"
    "  </log>                                                                   \n"
    " </modbus>                                                                 \n"
    "</modbusscope>                                                             \n"
);

// clang-format on
