'\" t
.\"     Title: modbus_write_bits
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 04/02/2014
.\"    Manual: Libmodbus Manual
.\"    Source: libmodbus 3.0.6
.\"  Language: English
.\"
.TH "MODBUS_WRITE_BITS" "3" "04/02/2014" "libmodbus 3\&.0\&.6" "Libmodbus Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
modbus_write_bits \- write many bits
.SH "SYNOPSIS"
.sp
\fBint modbus_write_bits(modbus_t *\fR\fB\fIctx\fR\fR\fB, int \fR\fB\fIaddr\fR\fR\fB, int \fR\fB\fInb\fR\fR\fB, const uint8_t *\fR\fB\fIsrc\fR\fR\fB);\fR
.SH "DESCRIPTION"
.sp
The \fImodbus_write_bits()\fR function shall write the status of the \fInb\fR bits (coils) from \fIsrc\fR at the address \fIaddr\fR of the remote device\&. The \fIsrc\fR array must contains bytes set to \fITRUE\fR or \fIFALSE\fR\&.
.sp
The function uses the Modbus function code 0x0F (force multiple coils)\&.
.SH "RETURN VALUE"
.sp
The \fImodbus_write_bits()\fR function shall return the number of written bits if successful\&. Otherwise it shall return \-1 and set errno\&.
.SH "ERRORS"
.PP
EMBMDATA
.RS 4
Writing too many bits
.RE
.SH "SEE ALSO"
.sp
\fBmodbus_read_bits\fR(3) \fBmodbus_write_bit\fR(3)
.SH "AUTHORS"
.sp
The libmodbus documentation was written by St\('ephane Raimbault <\m[blue]\fBstephane\&.raimbault@gmail\&.com\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "NOTES"
.IP " 1." 4
stephane.raimbault@gmail.com
.RS 4
\%mailto:stephane.raimbault@gmail.com
.RE
