# This is a generated file by dfetch. Don't edit this, but edit the manifest.
# For more info see https://dfetch.rtfd.io/en/latest/getting_started.html
dfetch:
  branch: master
  hash: c64ae03fd1f865ab0ea98d82637d40df
  last_fetch: 09/01/2025, 22:30:21
  patch: ''
  remote_url: https://github.com/lucide-icons/lucide.git
  revision: ''
  tag: v0.263.0
