dfetch:
  branch: master
  hash: e6a75aee954db0d94efe4a97947f0160
  last_fetch: 10/01/2022, 19:17:56
  patch: ''
  remote_url: https://github.com/beltoforion/muparser
  revision: 52ad02fe1f958fde041c246d24aaee3f40ae3fff
  tag: ''
