
@startuml System Context Diagram

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.8.0/C4_Container.puml

Person(endUser, "End user", "")
System(modbusscope, "ModbusScope", "Modbus Master")

System(bridge, "Bridge", "ModbusControl")
System(slave_tcp, "Device", "Modbus Slave (TCP or RTU)")
System(slave_rtu, "Device", "Modbus Slave (RTU)")

Rel(endUser, modbusscope, "controls", "GUI")
Rel(modbusscope, bridge, "polls", "Modbus TCP")
Rel(bridge, slave_rtu, "polls", "Modbus RTU")

Rel(modbusscope, slave_tcp, "polls", "Modbus TCP")

@enduml