dfetch:
  branch: master
  hash: e6a13587a1a50a35035d8d34a72d017e
  last_fetch: 10/01/2022, 19:37:54
  patch: ''
  remote_url: https://github.com/jgeudens/qcustomplot-release
  revision: ''
  tag: v2.1.0
