dfetch:
  branch: qt62_fix
  hash: 010f76eba28a5fb0ac2109ca97c1fda7
  last_fetch: 21/01/2022, 21:57:36
  patch: ''
  remote_url: https://github.com/jgeudens/qcustomplot-release
  revision: 3a0f90995d2baaaf005f4a17256a4829f39e60aa
  tag: ''
