name: Code quality analysis

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: docker://jgeudens/qt-linux:6.5.3_build_1
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start display server
      run: bash /start.sh &

    - name: Prepare environment for Ninja build with coverage
      run: |
        cmake . -GNinja -DUSE_GCOV=ON
        ninja

    - name: Generate gcovr coverage report
      run: |
        ctest
        gcovr -x > cobertura.xml

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        language: 'CPP'
        coverage-reports: cobertura.xml
      env:
        secrets.CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      if: "${{ (!!env.CODACY_PROJECT_TOKEN) }}"
