name: DFetch

on: push

jobs:
  dfetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up dfetch
      run: |
         python -m pip install --upgrade pip
         pip install https://github.com/dfetch-org/dfetch/archive/main.zip

    - name: Check dependencies
      run: dfetch check --sarif sarif.json

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif.json
