name: DFetch

on: push

jobs:
  dfetch:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Set up dfetch
      run: |
         python -m pip install --upgrade pip
         pip install https://github.com/dfetch-org/dfetch/archive/main.zip

    - name: Check dependencies
      run: dfetch check --sarif sarif.json

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: sarif.json
